### ISSUE TITLE
Postal code validation in OpenAPI schema

### ISSUE THREAD

**Issue by tuutti** [paytrail/api-documentation#34]
This is not really an issue with the documentation, but I don't know where else I should report this.

**Describe the bug**
OpenAPI schema expects postal code (in Address object) to only contain digits:

```yaml
Address:
  type: object
  properties:
    postalCode:
      type: string
      pattern: '^\d+$'
      example: '00100'
      maxLength: 15
      description: Postal code
```

Some countries have postal codes that contain spaces and non-digit characters as well, like the UK for example: https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom
